#!/bin/bash

ENHANCE_DIR=ONAME
CUR_DIR=`pwd`
CUR_PS1=$PS1

source $ENHANCE_DIR/paths

SHELL=${SHELL}

echo 'Enhance is active.'
# PS1='`hostname`:`pwd` \n\s-(Enh)\$ '
PS1='\[\e[1;35;47m\]\h\[\e[m\] \[\e[1;32m\]\w\[\e[m\]\n\s-\[\e[1;31m\](Enh)\[\e[m\]\$ '
export PS1

exec $SHELL

PS1=$CUR_PS1
echo "Left Enhance"
